# configurations for Jekyll
# http://jekyllrb.com/docs/configuration/#global-configuration
# https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/
safe: true
include: ["_test suite", "_structure"]

# https://blog.github.com/2017-11-29-use-any-theme-with-github-pages/
# https://github.com/pages-themes/tactile
title: Colorless echo JavaScript kit
description: The project aims to develop a JavaScript module framework that is simple to use with some interesting features.
show_downloads: true
theme: jekyll-theme-tactile

# https://help.github.com/articles/about-labels/#using-default-labels
